export const GET_STOCK = 'GET_STOCK';
export const CATCH_STOCK_ERROR = 'CATCH_STOCK_ERROR';
export const LOAD_STOCK = 'LOAD_STOCK';
export const GET_COMPANY = 'GET_COMPANY';
export const CATCH_COMPANY_ERROR = 'CATCH_COMPANY_ERROR';
export const LOAD_COMPANY = 'LOAD_COMPANY';
export const CHANGE_FILTER = 'CHANGE_FILTER';
